name: Check woningen

# Dit zorgt ervoor dat de workflow elke 5 minuten draait
on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:  # Hierdoor kun je hem ook handmatig starten

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checkout van je repository code
      - uses: actions/checkout@v3

      # Installeer Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Installeer de vereiste Python packages
      - run: pip install -r requirements.txt

      # Voer het Python script uit
      - run: python check_woningen.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
